FROM python:3.7

WORKDIR /usr/src/app

# Enable to run the container with PostgreSQL
# RUN pip3 install psycopg2

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

ENV FLASK_APP=./app.py
ENV FLASK_DEBUG=True

CMD ["python", "app.py"]
